[package]
name = "picotalk"
version = "0.1.0"
authors = ["Therese Kennerberg <tke@kth.se>"]

[dependencies]
cortex-m = "0.4"

[dependencies.stm32f0x0-hal]
version = "0.1.2"
features = ["rt", "unproven"]

[dependencies.embedded-hal]
version = "0.1.2"
features = ["unproven"]