[package]
name = "picorunner"
version = "0.1.0"
authors = ["tke <tke@kth.se>"]

[dependencies]
picotalk = { path = "../picotalk/" }
[dependencies.embedded-hal]
version = "0.1.2"
features = ["unproven"]
