[package]
name = "stm32f0x0"
version = "0.1.0"
authors = ["Teo Klestrup Röijezon <teo@nullable.se>"]

[dependencies]
bare-metal = "0.1"
vcell = "0.1"
cortex-m = "0.4"

[dependencies.cortex-m-rt]
optional = true
version = "0.4.0"
# version = "0.3.15"

[features]
rt = ["cortex-m-rt"]
