#+TITLE: Exercises for programming the PicoNodes
#+AUTHOR: Therese Kennerberg
# Fancy links
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{colorlinks, linkcolor={red!50!black}, citecolor={blue!50!black}, urlcolor={blue!80!black}}

* Programming Exercises

This document provides the user with tasks to practice when using the PicoNode kit.

** Task one: Light it up
Make one LED on the PicoNode-LED light up by using an other node to transmit a value to it.
Do this by:
1. Using the switch-node
2. Program a PicoNode-compute
** Task two: Stick your finger to it
Transmit a value to the LED-node with a PicoNode-compute as a middleman.
** Task three: Adder
Program a compute-node to add one to the value received.
** Task four: adding and subbing
Program the compute-node to add the value one if receiving one and subtracting the value one if receiving two.
** Task five: The chain
Use four nodes of you choosing to make a communication chain.
** Task six: Three reaction adder
Program the compute-node to add three values received from the right to acc.
** Task seven: Dumb RNG
Make a random number generator in range 1-4. The number should be generated by pressing the switch-node and then displayed on the LED node,
using the compute-node as a middleman.
