#+TITLE: Title Template for Degree Project
#+SUBTITLE: SUBTITLE - Arial 16/19pt
#+AUTHOR: Therese Kennerberg, Teo Klestrup Röijezon

* Introduction
** Background
***** Use references
** Problem
***** Use references
** Purpose
** Goal
*** Benefits, Ethics and Sustainability
** Methodology / Methods

The product will have the UI designed in the browser so the user wont be fixed to one plattform. This way eather a mobilephone or a laptop can be used for programming the microcontrollers. The MCU of our choice is stm32f030f4p6. This MCU is chosen because it got enough I/Os and memoryspace for the application and is reasonable cheep. This MCUs are also popular to program in Rust which make it easier to find documentation and support. At least 8 I/O is needed. UART communication(two pins for Tx and Rx), communications between the MCUs(4 pins), external clocksource and coarsegrain syncronization clock. A server will be provided by Inicio which contains the drivers for communicating between the plattforms and the compiler for the bytecode.

*** IDE and programming langueges 

Rust is used to program the MCU. The MCU of our choice for the is 
stm32f030f4p6. C is also an option and can be prefered 
if anyone would like to use IDE such as EWARM or STM32Cube to generate 
initiallisation code but is not suported by Linux. Rust is better from a safety 
perspective because it is harder to read something from more then one thread 
and it verifies pointers are still alive when they are used so you will not be 
able to keep a pointer beyond their objects lifetime. Rust also suits very well 
with our Bytecode model since our abstract sytax tree contains different legal 
values depending on the instruction. Alot of different IDE can be used for Rust,
in this project we will use Emacs because both Scala program and the report is 
written here. 

The homepage is programmed in Scala. Scala is very practical for not changing 
languege when writing the client and server. This makes it easier when communicating 
between the server and client.

*** CAD and CAM tools
In the first stages of the project it is prefered to be more flexible for changes. 
For this reason a breadboard and jumpingwires are used to test the design before 
making the final one. The MCU-moduels is made in a router  mill so a breakout board
can be made for the MCU pins to match the breadboard. DipTrace is used for designing 
and routing the PCBs. 




***** Use references!
** Delimitations (Avgränsningar, swe)
** Outline (Disposition)
* (Theoretic Background) Use a self-explaining title
** Use headings to break the text
* (Engineering-related content, Methodologies and Methods) Use a self-explaining title
** Engineering-related and scientific content:
** (The work)
** (Result)
** (Conclusions)
