#+TITLE: User Manual for the PicoNode-Led
#+AUTHOR: Therese Kennerberg

* Introduction

The PicoNode-LED is designed to be used with the PicoNode kit and is compatible with the PicoNode kits motherboard.
It is meant to give a more hands-on and visual understanding of the communication between the PicoNodes. This node
is not programmable by the user but is already running a program designed to be used with the motherboard.

* Features

The PicoNode-LED offers the following features:

- One red LED to symbolize one.
- One blue LED to symbolize two.
- One green LED to symbolize three.
- One yellow LED to symbolize four.

* Getting started

Follow these steps to learn how to use the PicoNode-LED:

1. Power the motherboard
2. Place the PicoNode-LED on a available slot on the motherboard. This slot should also have one available slot in any direction next to the PicoNode-LED.
3. Place the PicoNode-Switch on the available slot next to the PicoNode-LED
4. If you placed a switch then press a button, and a LED will light up symbolizing the value received.

* Hardware and layout

The hardware and the PCB-layout are available in the data sheet provided for the PicoNode kit.

* LEDs

The LEDs are used to symbolize a value received from one of the input pins. There are four input pins for receiving a value, one in each direction. The PicoNode-LED will only receive a value in the range of 1-4. If it receives a value out of range, then no LED will light up. (Should it be able to receive more then one direction?)
