#+TITLE: User Manual for the PICONODE-LED
#+SUBTITLE: SUBTITLE - Arial 16/19pt
#+AUTHER: Therese Kennerberg

* Instruduction

The PicoNode-LED is designed to be used with the PicoNode kit and is compatible with the PicoNode kits motherboard. It is meant to give a more handson and visual understanding of the communication between the PicoNodes. This node is not programmable by the user but is already running a program designed to be used with the motherboard.

* Features

The PicoNode-LED offers the following features:

- One red LED to symbolize one.
- One blue LED to symbolize two.
- One green LED to symbolize three.
- One yellow LED to symbolize four.

* Quick start

The node is an easy applied feature for the PicoNode kit developed for the basic in hardware close programming and distributed systems.

* Getting started

Follow these steps to learn how to use the PicoNode-LED:

1. Power the motherboard
2. Place the PicoNode-LED on a available slot on the motherboard. This slot should also have one available slot in any direction next to the PicoNode-LED.
3. Place the PicoNode-Switch on the available slot next to the PicoNode-LED
4. If you placed a switch then press a button, and a LED will light up symbolizing the value recieved.

* Hardware and layout

The hardware and the PCB-layout are available in the datasheet provided for the PicoNode kit.

* LEDs

The LEDs are used to symbolize a value recieved from one of the input pins. There are four input pins for recieving a value, one in each directino. The PicoNode-LED will only recieve a value in the range of 1-4. If it recieves a value out of range, then no LED will light up. (Should it be able to recieve more then one direction?)
